# Generated by Django 4.1.7 on 2023-11-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='was_found',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ButtonLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.autopost')),
            ],
        ),
    ]
