# Generated by Django 4.1.7 on 2023-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_autopost_searchhistory_was_found_buttonlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonlinks',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
