# Generated by Django 4.1.7 on 2023-11-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_buttonlinks_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='referral_link',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
