version: "3.7"
services:
  redis:
    image: redis:apline
    command:
      - redis-server
    restart: on-failure
    ports:
      - "6379:6379"
  db:
    image: postgres:14-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  
  bot:
    build: .
    command: sh -c "python3 main.py"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - redis


volumes:
  pgdata:
