version: "3.7"
services:
  bot:
    build: .
    command: sh -c "python3 main.py"
    env_file:
      - .env
    restart: always
    network_mode: host
  reserve_bot:
    build: ./reserve_bot/
    command: sh -c "python3 main.py"
    restart: always
    network_mode: host
